### ISSUE TITLE
Evaluate effect of removing list semantics in nav

### ISSUE THREAD

**Issue by davidluhr** [mozdevs/cssremedy#21] opened 2019-02-11 16:57 UTC
There has been recent discussion around the impact `list-style: none;` has on screen readers, particularly VoiceOver. [Sara Soueidan Tweeted that this removes `<ul>/<li>` semantics in VoiceOver](https://twitter.com/sarasoueidan/status/1083734801952182272), and [Scott O'Hara recently wrote about this in greater length](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html).

Is this remedy intentionally removing these semantics within a `<nav>`?

https://github.com/mozdevs/cssremedy/blob/20be8a0abcd3cdfba32b3cbe2c2c7d7d5acb5036/remedy.css#L67

**Comment by jensimmons** [comment] 2019-02-11 18:44
This issue is a duplicate of https://github.com/mozdevs/cssremedy/issues/15

**Closed by jensimmons** 2019-02-11 18:44 UTC
Labels: duplicate
